### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by StefanJanssen95** [Codasylph/CodaTech#1]
When launching the game it crashes immediately.
**MC**: 1.14
**CodaTech**: 1.14-1.0.2a
```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors!
	at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:45)
	at net.fabricmc.loader.entrypoint.hooks.EntrypointClient.start(EntrypointClient.java:34)
	at net.minecraft.class_310.method_1503(class_310.java)
	at net.minecraft.class_310.method_1514(class_310.java:395)
	at net.minecraft.client.main.Main.main(Main.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:127)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
	Suppressed: java.lang.BootstrapMethodError: java.lang.IllegalAccessError: no such constructor: me.codasylph.codatech.block.entity.RedstoneCrusherBlockEntity.<init>()void/newInvokeSpecial
		at me.codasylph.codatech.init.CTRegistry.<clinit>(CTRegistry.java:21)
		at me.codasylph.codatech.CodaTech.onInitialize(CodaTech.java:11)
		at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.lambda$logErrors$0(EntrypointUtils.java:38)
		at java.util.ArrayList.forEach(Unknown Source)
		at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:36)
		... 19 more
	Caused by: java.lang.IllegalAccessError: no such constructor: me.codasylph.codatech.block.entity.RedstoneCrusherBlockEntity.<init>()void/newInvokeSpecial
		at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(Unknown Source)
		... 24 more
	Caused by: java.lang.NoClassDefFoundError: com/raphydaphy/crochet/network/IPacket
		at java.lang.invoke.MethodHandleNatives.resolve(Native Method)
		at java.lang.invoke.MemberName$Factory.resolve(Unknown Source)
		at java.lang.invoke.MemberName$Factory.resolveOrFail(Unknown Source)
		at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(Unknown Source)
		at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(Unknown Source)
		... 25 more
	Caused by: java.lang.ClassNotFoundException: com.raphydaphy.crochet.network.IPacket
		at java.net.URLClassLoader.findClass(Unknown Source)
		at java.lang.ClassLoader.loadClass(Unknown Source)
		at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
		at java.lang.ClassLoader.loadClass(Unknown Source)
		at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:160)
		at java.lang.ClassLoader.loadClass(Unknown Source)
		... 30 more

```

**Comment by Codasylph** [comment]
Please make sure Crochet is installed, it is a dependency of the mod.
